### ISSUE TITLE
Readme installation of Vue

### ISSUE THREAD

**Issue by byco** [osucovid/covid_capstone#2]
This isn't really an issue, more of a note to follow up since these weren't mentioned in the Readme.... I just picked the first option out of these.

are we using Vue 2.x or 3.x preview?

There are two Sass/SCSS options when installing Vue:
> Sass/SCSS (with dart-sass)
  Sass/SCSS (with node-sass)

Remember to "npm install" in the client folder before starting the server. :)

**Comment by chosunosu** [comment]
We are using Vue 2.x!

**Comment by byco** [comment]
What about the Sass/SCSS options?

**Comment by chosunosu** [comment]
dart-sass : )
